name: Deploy no Kubernetes
on: 
    workflow_call:  

jobs:
    deploy:
        name: "Deploy"
        runs-on: ubuntu-latest
        steps:
           - name: Obtendo o c√≥digo
             uses: actions/checkout@v4
             with:
                method: kubeconfig
                kubeconfig: ${{ secrets.K8S_CONFIG }}
        
           - name: Deploy no Kubernetes
             uses: Azure/k8s-deploy@v5
             with:
                resource-group: yourResourceGroup
                name: yourClusterName
                action: deploy
                strategy: basic

                private-cluster: true
                manifests: |
                    k8s/deployment.yaml
                images: |
                    niltonpita/projeto-devops-pro:v${{ github.run_number }} 
